---
title: "Course Schedule"
---

| Module                       | Date                               | Topics                                                                               |
| --                           | --                                 | --                                                                                   |
| Getting started with Python  | 09-22 (stream A), 09-23 (stream B) | Installing Python - how to run Python programs - managing Python environments        |
| Python language fundamentals | 09-24 (stream A), 09-24 (stream B) | Object types - list - dictionaries - tuples - sets - files                           |
| ...                          | 09-25 (stream A), 09-29 (stream B) | Statements - control flows - while and for loops - iterations and comprhensions      |
| Computing with NumPy         | 10-1 (stream A), 10-2 (stream B)   | Array creation - manipulation - functions - statistics - linear algebra - generators |
| Pandas for data analysis     | 10-2 (stream A), 10-6 (stream B)   | Dataframes - querying - manipulation - 'time' data                                   |
| ...                          | 10-8 (stream A), 10-8 (stream B)   | Grouping - working with multiple dataframes - IO                                     |

::: {.callout-note}
## Adjustments and Updates

This schedule is subject to change based on:

- Class progress and needs
- University calendar changes
- Unexpected closures

All changes will be announced in class and posted on the course website.
:::
